import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import accountsRouter from "./accounts";
import contactsRouter from "./contacts";
import leadsRouter from "./leads";
import dashboardRouter from "./dashboard";
import productsRouter from "./products";
import quotationsRouter from "./quotations";
import estimationsRouter from "./estimations";
import approvalsRouter from "./approvals";
import salesOrdersRouter from "./sales_orders";
import projectsRouter from "./projects";
import projectMilestonesRouter from "./project_milestones";
import projectTasksRouter from "./project_tasks";
import projectTeamRouter from "./project_team";
import siteSurveysRouter from "./site_surveys";
import serviceTicketsRouter from "./service_tickets";
import serviceVisitsRouter from "./service_visits";
import amcContractsRouter from "./amc_contracts";
import invoicesRouter from "./invoices";
import paymentsRouter from "./payments";
import creditNotesRouter from "./credit_notes";
import financialRouter from "./financial";
import vendorsRouter from "./vendors";
import purchaseOrdersRouter from "./purchase_orders";
import grnsRouter from "./grns";
import vendorInvoicesRouter from "./vendor_invoices";
import vendorPaymentsRouter from "./vendor_payments";
import expensesRouter from "./expenses";
import procurementDashboardRouter from "./procurement_dashboard";
import notificationsRouter from "./notifications";
import companySettingsRouter from "./company_settings";
import staffRouter from "./staff";
import emailTemplatesRouter from "./email_templates";
import emailSettingsRouter from "./email_settings";
import emailsRouter from "./emails";
import integrationsRouter from "./integrations";
import storageRouter from "./storage";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(accountsRouter);
router.use(contactsRouter);
router.use(leadsRouter);
router.use(dashboardRouter);
router.use(productsRouter);
router.use(quotationsRouter);
router.use(estimationsRouter);
router.use(approvalsRouter);
router.use(salesOrdersRouter);
router.use(projectsRouter);
router.use(projectMilestonesRouter);
router.use(projectTasksRouter);
router.use(projectTeamRouter);
router.use(siteSurveysRouter);
router.use(serviceTicketsRouter);
router.use(serviceVisitsRouter);
router.use(amcContractsRouter);
router.use(invoicesRouter);
router.use(paymentsRouter);
router.use(creditNotesRouter);
router.use(financialRouter);
router.use(vendorsRouter);
router.use(purchaseOrdersRouter);
router.use(grnsRouter);
router.use(vendorInvoicesRouter);
router.use(vendorPaymentsRouter);
router.use(expensesRouter);
router.use(procurementDashboardRouter);
router.use(notificationsRouter);
router.use(companySettingsRouter);
router.use(staffRouter);
router.use(emailTemplatesRouter);
router.use(emailSettingsRouter);
router.use(emailsRouter);
router.use(integrationsRouter);
router.use(storageRouter);

export default router;
